"""
Agricultural Diagnostic Engine - Chemical Database

Phase 3: Safety-First Chemical Treatment Recommendations

This module provides a verified, hard-coded database of approved chemical
treatments for common crop pests and diseases. It enforces strict safety
protocols and regional restrictions.

Key Principle: Chemical recommendations come from verified, approved sources
ONLY - never generated by LLM to prevent unsafe dosing.

Author: Backend Engineering Team
Version: 1.0.0
"""

from typing import Optional, Dict, List
from enum import Enum
from dataclasses import dataclass, asdict
import json


# ============================================================================
# ENUMERATIONS
# ============================================================================

class Region(str, Enum):
    """Geographic regions with different regulatory approvals."""
    NORTH_AMERICA = "North America"
    EUROPE = "Europe"
    ASIA = "Asia"
    AUSTRALIA = "Australia"
    SOUTH_AMERICA = "South America"
    AFRICA = "Africa"
    WORLDWIDE = "Worldwide"


class ChemicalClass(str, Enum):
    """Chemical classification for pesticides."""
    FUNGICIDE = "Fungicide"
    INSECTICIDE = "Insecticide"
    ACARICIDE = "Acaricide"
    HERBICIDE = "Herbicide"
    NEMATICIDE = "Nematicide"
    BACTERICIDE = "Bactericide"


class ToxicityLevel(str, Enum):
    """WHO toxicity classification."""
    IA_EXTREMELY_HAZARDOUS = "Ia - Extremely Hazardous"
    IB_HIGHLY_HAZARDOUS = "Ib - Highly Hazardous"
    II_MODERATELY_HAZARDOUS = "II - Moderately Hazardous"
    III_SLIGHTLY_HAZARDOUS = "III - Slightly Hazardous"
    IV_UNLIKELY_TO_PRESENT = "IV - Unlikely to Present Hazard"


# ============================================================================
# DATA MODELS
# ============================================================================

@dataclass
class PPERequirement:
    """Personal protective equipment requirements."""
    gloves: str  # Type of gloves (e.g., "nitrile rubber")
    respirator: str  # Respirator type (e.g., "P2/N95" or "None")
    eye_protection: str  # Eye protection (e.g., "chemical splash goggles")
    clothing: str  # Clothing requirements
    boots: str  # Footwear requirements
    
    def to_list(self) -> List[str]:
        """Convert to list format for DiagnosticResult."""
        items = []
        if self.gloves and self.gloves != "None":
            items.append(f"Gloves ({self.gloves})")
        if self.respirator and self.respirator != "None":
            items.append(f"Respirator ({self.respirator})")
        if self.eye_protection and self.eye_protection != "None":
            items.append(f"Eye protection ({self.eye_protection})")
        if self.clothing and self.clothing != "None":
            items.append(self.clothing)
        if self.boots and self.boots != "None":
            items.append(self.boots)
        return items if items else ["Standard safety precautions"]


@dataclass
class ChemicalTreatmentData:
    """Approved chemical treatment with strict safety requirements."""
    product_name: str
    active_ingredient: str
    concentration: str  # e.g., "75% w/w"
    chemical_class: ChemicalClass
    toxicity_level: ToxicityLevel
    dosage: str  # e.g., "1.2-1.8 kg/ha" or "30-50 ml/100L water"
    application_method: str  # e.g., "Foliar spray", "Soil drench"
    application_frequency: str  # e.g., "Every 10-14 days"
    pre_harvest_interval: int  # Days before harvest (0 = anytime)
    re_entry_interval: str  # e.g., "48 hours"
    ppe_required: PPERequirement
    approved_regions: List[Region]
    approved_crops: List[str]  # Crops this treatment is approved for
    environmental_notes: str
    effectiveness_rate: float  # 0.0-1.0
    restrictions: Optional[str] = None  # Regional or temporal restrictions
    
    def is_approved_for(self, region: Region, crop: str) -> bool:
        """Check if treatment is approved for region and crop."""
        region_approved = (
            Region.WORLDWIDE in self.approved_regions or 
            region in self.approved_regions
        )
        crop_approved = crop.lower() in [c.lower() for c in self.approved_crops]
        return region_approved and crop_approved
    
    def to_dict(self) -> dict:
        """Convert to dictionary, handling dataclass fields."""
        data = asdict(self)
        data["ppe_required"] = asdict(self.ppe_required)
        data["chemical_class"] = self.chemical_class.value
        data["toxicity_level"] = self.toxicity_level.value
        data["approved_regions"] = [r.value for r in self.approved_regions]
        return data


@dataclass
class SafeTreatmentFallback:
    """Fallback response when chemical is not in database."""
    product_name: str = "Consult Local Expert"
    active_ingredient: str = "Unknown - Verify with local agricultural extension"
    dosage: str = "Contact local expert or agricultural advisor"
    application_frequency: str = "As recommended by expert"
    pre_harvest_interval: int = 0
    re_entry_interval: str = "As per local regulations"
    ppe_required: List[str] = None
    environmental_notes: str = "Unknown chemical - requires expert consultation"
    effectiveness_rate: float = 0.0
    is_fallback: bool = True
    
    def __post_init__(self):
        if self.ppe_required is None:
            self.ppe_required = ["Consult local expert for safety requirements"]
    
    def to_dict(self) -> dict:
        return asdict(self)


# ============================================================================
# CHEMICAL DATABASE
# ============================================================================

class ChemicalDatabase:
    """
    Verified database of approved chemical treatments for crop pests and diseases.
    
    This database ensures that chemical recommendations are NOT generated by LLM
    but retrieved from hard-coded, approved sources. All dosages, safety
    requirements, and restrictions are pre-validated.
    
    SAFETY PRINCIPLE:
    Never generate chemical treatments dynamically. Always reference this database.
    If a pest/chemical is not in the database, return a fallback recommendation
    to consult a local expert.
    """
    
    def __init__(self):
        """Initialize the chemical database."""
        self._treatments = self._build_database()
    
    def _build_database(self) -> Dict[str, List[ChemicalTreatmentData]]:
        """
        Build the chemical treatment database.
        
        Returns:
            Dictionary keyed by pest/disease name with list of approved treatments.
        """
        return {
            # ================================================================
            # TOMATO DISEASES & PESTS
            # ================================================================
            
            "Early Blight (Alternaria solani)": [
                ChemicalTreatmentData(
                    product_name="Chlorothalonil 75% WP",
                    active_ingredient="Chlorothalonil 75% w/w",
                    concentration="75%",
                    chemical_class=ChemicalClass.FUNGICIDE,
                    toxicity_level=ToxicityLevel.II_MODERATELY_HAZARDOUS,
                    dosage="1.2-1.8 kg/ha in 400-600 L water",
                    application_method="Foliar spray",
                    application_frequency="Every 10-14 days",
                    pre_harvest_interval=7,
                    re_entry_interval="48 hours",
                    ppe_required=PPERequirement(
                        gloves="Heavy-duty rubber",
                        respirator="P2/N95",
                        eye_protection="Chemical splash goggles",
                        clothing="Long-sleeved shirt and pants",
                        boots="Closed-toe boots"
                    ),
                    approved_regions=[
                        Region.NORTH_AMERICA,
                        Region.EUROPE,
                        Region.AUSTRALIA
                    ],
                    approved_crops=["Tomato", "Potato", "Cucumber"],
                    environmental_notes="Avoid application near water sources. Harmful to aquatic organisms.",
                    effectiveness_rate=0.88
                ),
                ChemicalTreatmentData(
                    product_name="Copper Fungicide (Bordeaux)",
                    active_ingredient="Copper sulfate pentahydrate 50% + Lime 50%",
                    concentration="50%",
                    chemical_class=ChemicalClass.FUNGICIDE,
                    toxicity_level=ToxicityLevel.III_SLIGHTLY_HAZARDOUS,
                    dosage="50-100 g per 10 L water",
                    application_method="Foliar spray",
                    application_frequency="Every 7-10 days",
                    pre_harvest_interval=3,
                    re_entry_interval="24 hours",
                    ppe_required=PPERequirement(
                        gloves="Nitrile gloves",
                        respirator="None",
                        eye_protection="Safety glasses",
                        clothing="Long sleeves",
                        boots="Closed-toe boots"
                    ),
                    approved_regions=[Region.WORLDWIDE],
                    approved_crops=["Tomato", "Grape", "Apple"],
                    environmental_notes="Less toxic than synthetic fungicides. Organic-approved in many regions.",
                    effectiveness_rate=0.72
                )
            ],
            
            "Late Blight (Phytophthora infestans)": [
                ChemicalTreatmentData(
                    product_name="Mancozeb 80% WP",
                    active_ingredient="Mancozeb 80% w/w",
                    concentration="80%",
                    chemical_class=ChemicalClass.FUNGICIDE,
                    toxicity_level=ToxicityLevel.III_SLIGHTLY_HAZARDOUS,
                    dosage="1.5-2.5 kg/ha in 400-600 L water",
                    application_method="Foliar spray",
                    application_frequency="Every 10-14 days",
                    pre_harvest_interval=5,
                    re_entry_interval="48 hours",
                    ppe_required=PPERequirement(
                        gloves="Rubber gloves",
                        respirator="P2/N95",
                        eye_protection="Goggles",
                        clothing="Long sleeves and pants",
                        boots="Closed-toe boots"
                    ),
                    approved_regions=[
                        Region.NORTH_AMERICA,
                        Region.EUROPE,
                        Region.AUSTRALIA
                    ],
                    approved_crops=["Potato", "Tomato", "Grape"],
                    environmental_notes="Monitor water runoff. Can accumulate in soil over time.",
                    effectiveness_rate=0.85,
                    restrictions="Not approved in some EU countries due to environmental concerns"
                ),
                ChemicalTreatmentData(
                    product_name="Metalaxyl-M 25% + Mancozeb 65% WS",
                    active_ingredient="Metalaxyl-M 25% + Mancozeb 65%",
                    concentration="Combination",
                    chemical_class=ChemicalClass.FUNGICIDE,
                    toxicity_level=ToxicityLevel.III_SLIGHTLY_HAZARDOUS,
                    dosage="2-2.5 kg/ha in 400-600 L water",
                    application_method="Foliar spray",
                    application_frequency="Every 7-14 days",
                    pre_harvest_interval=7,
                    re_entry_interval="48 hours",
                    ppe_required=PPERequirement(
                        gloves="Rubber gloves",
                        respirator="P2/N95",
                        eye_protection="Goggles",
                        clothing="Long sleeves and pants",
                        boots="Closed-toe boots"
                    ),
                    approved_regions=[
                        Region.NORTH_AMERICA,
                        Region.EUROPE,
                        Region.ASIA
                    ],
                    approved_crops=["Potato", "Tomato"],
                    environmental_notes="Systemic action provides preventive protection.",
                    effectiveness_rate=0.90
                )
            ],
            
            "Powdery Mildew": [
                ChemicalTreatmentData(
                    product_name="Sulfur 80% WP",
                    active_ingredient="Elemental sulfur 80%",
                    concentration="80%",
                    chemical_class=ChemicalClass.FUNGICIDE,
                    toxicity_level=ToxicityLevel.IV_UNLIKELY_TO_PRESENT,
                    dosage="30-50 kg/ha or 3-5 kg per 100L water",
                    application_method="Dust or spray",
                    application_frequency="Every 5-7 days",
                    pre_harvest_interval=1,
                    re_entry_interval="12 hours",
                    ppe_required=PPERequirement(
                        gloves="Cotton gloves",
                        respirator="Dust mask if dusting",
                        eye_protection="Safety glasses",
                        clothing="Long sleeves (optional)",
                        boots="Closed-toe boots"
                    ),
                    approved_regions=[Region.WORLDWIDE],
                    approved_crops=["Tomato", "Grape", "Cucumber", "Melon"],
                    environmental_notes="Organic-approved fungicide. Very low toxicity.",
                    effectiveness_rate=0.85
                ),
                ChemicalTreatmentData(
                    product_name="Bupirimate 25% + Triflumizole 5% SC",
                    active_ingredient="Bupirimate 25% + Triflumizole 5%",
                    concentration="Combination",
                    chemical_class=ChemicalClass.FUNGICIDE,
                    toxicity_level=ToxicityLevel.III_SLIGHTLY_HAZARDOUS,
                    dosage="1.0 L/ha in 400-600 L water",
                    application_method="Foliar spray",
                    application_frequency="Every 10-14 days",
                    pre_harvest_interval=5,
                    re_entry_interval="24 hours",
                    ppe_required=PPERequirement(
                        gloves="Nitrile gloves",
                        respirator="None",
                        eye_protection="Safety glasses",
                        clothing="Long sleeves",
                        boots="Closed-toe boots"
                    ),
                    approved_regions=[
                        Region.NORTH_AMERICA,
                        Region.EUROPE,
                        Region.ASIA
                    ],
                    approved_crops=["Tomato", "Grape", "Cucumber"],
                    environmental_notes="Low toxicity to beneficial insects.",
                    effectiveness_rate=0.90
                )
            ],
            
            # ================================================================
            # POTATO DISEASES & PESTS
            # ================================================================
            
            "Colorado Potato Beetle": [
                ChemicalTreatmentData(
                    product_name="Spinosad 48% SC",
                    active_ingredient="Spinosad (mixture of spinosyns A and D) 48%",
                    concentration="48%",
                    chemical_class=ChemicalClass.INSECTICIDE,
                    toxicity_level=ToxicityLevel.III_SLIGHTLY_HAZARDOUS,
                    dosage="250-375 ml/ha in 400-500 L water",
                    application_method="Foliar spray",
                    application_frequency="Every 5-10 days as needed",
                    pre_harvest_interval=3,
                    re_entry_interval="12 hours",
                    ppe_required=PPERequirement(
                        gloves="Nitrile gloves",
                        respirator="None",
                        eye_protection="Safety glasses",
                        clothing="Long sleeves",
                        boots="Closed-toe boots"
                    ),
                    approved_regions=[Region.WORLDWIDE],
                    approved_crops=["Potato", "Tomato", "Cabbage"],
                    environmental_notes="Organic-approved. Low mammalian toxicity.",
                    effectiveness_rate=0.82
                ),
                ChemicalTreatmentData(
                    product_name="Imidacloprid 35% SC",
                    active_ingredient="Imidacloprid 35%",
                    concentration="35%",
                    chemical_class=ChemicalClass.INSECTICIDE,
                    toxicity_level=ToxicityLevel.II_MODERATELY_HAZARDOUS,
                    dosage="250-300 ml/ha in 400-500 L water",
                    application_method="Foliar spray or seed dressing",
                    application_frequency="As needed, typically once per season",
                    pre_harvest_interval=14,
                    re_entry_interval="48 hours",
                    ppe_required=PPERequirement(
                        gloves="Nitrile gloves",
                        respirator="P2/N95",
                        eye_protection="Safety glasses",
                        clothing="Long sleeves and pants",
                        boots="Closed-toe boots"
                    ),
                    approved_regions=[
                        Region.NORTH_AMERICA,
                        Region.EUROPE,
                        Region.AUSTRALIA
                    ],
                    approved_crops=["Potato", "Tomato", "Citrus"],
                    environmental_notes="Neonicotinoid - restricted in some EU countries due to bee concerns.",
                    effectiveness_rate=0.95,
                    restrictions="Check local regulations regarding neonicotinoid use"
                )
            ],
            
            # ================================================================
            # CORN DISEASES & PESTS
            # ================================================================
            
            "Gray Leaf Spot": [
                ChemicalTreatmentData(
                    product_name="Pyraclostrobin 25% EC",
                    active_ingredient="Pyraclostrobin 25%",
                    concentration="25%",
                    chemical_class=ChemicalClass.FUNGICIDE,
                    toxicity_level=ToxicityLevel.III_SLIGHTLY_HAZARDOUS,
                    dosage="750-1000 ml/ha in 200-400 L water",
                    application_method="Foliar spray",
                    application_frequency="Every 14-21 days",
                    pre_harvest_interval=14,
                    re_entry_interval="24 hours",
                    ppe_required=PPERequirement(
                        gloves="Nitrile gloves",
                        respirator="None",
                        eye_protection="Safety glasses",
                        clothing="Long sleeves",
                        boots="Closed-toe boots"
                    ),
                    approved_regions=[
                        Region.NORTH_AMERICA,
                        Region.EUROPE
                    ],
                    approved_crops=["Corn", "Wheat", "Barley"],
                    environmental_notes="Systemic and translaminar action.",
                    effectiveness_rate=0.88
                )
            ],
            
            # ================================================================
            # WHEAT DISEASES
            # ================================================================
            
            "Fusarium Head Blight": [
                ChemicalTreatmentData(
                    product_name="Azoxystrobin 25% EC",
                    active_ingredient="Azoxystrobin 25%",
                    concentration="25%",
                    chemical_class=ChemicalClass.FUNGICIDE,
                    toxicity_level=ToxicityLevel.III_SLIGHTLY_HAZARDOUS,
                    dosage="600-900 ml/ha in 200-400 L water",
                    application_method="Foliar spray",
                    application_frequency="At flowering stage, may repeat 7-10 days later",
                    pre_harvest_interval=21,
                    re_entry_interval="24 hours",
                    ppe_required=PPERequirement(
                        gloves="Nitrile gloves",
                        respirator="None",
                        eye_protection="Safety glasses",
                        clothing="Long sleeves",
                        boots="Closed-toe boots"
                    ),
                    approved_regions=[
                        Region.NORTH_AMERICA,
                        Region.EUROPE,
                        Region.AUSTRALIA
                    ],
                    approved_crops=["Wheat", "Barley", "Corn"],
                    environmental_notes="Critical application timing at anthesis stage.",
                    effectiveness_rate=0.75
                )
            ],
        }
    
    def get_safe_treatment(
        self,
        pest_name: str,
        region: Region = Region.NORTH_AMERICA,
        crop: str = "general"
    ) -> List[Dict]:
        """
        Safely retrieve approved chemical treatments for a pest.
        
        PARAMETERS:
        ===========
        pest_name : str
            Name of the pest or disease (e.g., "Early Blight (Alternaria solani)")
            
        region : Region or str
            Geographic region (e.g., "North America", "Europe")
            
        crop : str
            Crop type for additional filtering (e.g., "tomato", "potato")
            
        RETURNS:
        ========
        List[Dict]
            List of approved treatments with all safety metadata.
            If pest not found or not approved for region, returns fallback.
            
        EXAMPLE:
        ========
        >>> db = ChemicalDatabase()
        >>> treatments = db.get_safe_treatment(
        ...     "Early Blight (Alternaria solani)",
        ...     Region.NORTH_AMERICA,
        ...     "tomato"
        ... )
        >>> for treatment in treatments:
        ...     print(f"{treatment['product_name']}: {treatment['dosage']}")
        """
        # Normalize region
        if isinstance(region, str):
            try:
                region = Region(region)
            except ValueError:
                region = Region.NORTH_AMERICA  # Default region
        
        # Look up pest in database
        treatments = self._treatments.get(pest_name, [])
        
        # Filter by region and crop
        approved_treatments = []
        for treatment in treatments:
            if treatment.is_approved_for(region, crop):
                approved_treatments.append(treatment.to_dict())
        
        # Return approved treatments or fallback
        if approved_treatments:
            return approved_treatments
        else:
            # Return fallback with explanation
            fallback = SafeTreatmentFallback()
            return [fallback.to_dict()]
    
    def get_treatment_for_pest(
        self,
        pest_name: str,
        region: str = "North America"
    ) -> Dict:
        """
        Get single approved treatment (primary option).
        
        PARAMETERS:
        ===========
        pest_name : str
            Pest or disease name
            
        region : str
            Region (converted to Region enum)
            
        RETURNS:
        ========
        Dict
            Single treatment dictionary or fallback object
        """
        try:
            region_enum = Region(region)
        except ValueError:
            region_enum = Region.NORTH_AMERICA
        
        treatments = self.get_safe_treatment(pest_name, region_enum)
        return treatments[0] if treatments else SafeTreatmentFallback().to_dict()
    
    def is_pest_in_database(self, pest_name: str) -> bool:
        """Check if pest is in the database."""
        return pest_name in self._treatments
    
    def get_all_pests(self) -> List[str]:
        """Get list of all pests in the database."""
        return list(self._treatments.keys())
    
    def get_ppe_requirements(self, pest_name: str) -> List[str]:
        """
        Get PPE requirements for a pest's treatments.
        
        Returns list of PPE items across all treatments for the pest.
        """
        treatments = self._treatments.get(pest_name, [])
        if not treatments:
            return ["Consult local expert"]
        
        # Combine PPE from first approved treatment
        first_treatment = treatments[0]
        return first_treatment.ppe_required.to_list()
    
    def get_pre_harvest_interval(self, pest_name: str) -> int:
        """
        Get minimum pre-harvest interval for a pest.
        
        Returns the longest interval from all treatments.
        """
        treatments = self._treatments.get(pest_name, [])
        if not treatments:
            return 14  # Default safe value
        
        return max(t.pre_harvest_interval for t in treatments)


# ============================================================================
# EXAMPLE USAGE
# ============================================================================

if __name__ == "__main__":
    print("=" * 80)
    print("Chemical Database - Examples")
    print("=" * 80)
    
    db = ChemicalDatabase()
    
    # Example 1: Get treatments for Early Blight in North America
    print("\n[EXAMPLE 1: Early Blight - North America]")
    print("-" * 80)
    treatments = db.get_safe_treatment(
        "Early Blight (Alternaria solani)",
        Region.NORTH_AMERICA,
        "tomato"
    )
    for i, treatment in enumerate(treatments, 1):
        print(f"\nOption {i}:")
        print(f"  Product: {treatment['product_name']}")
        print(f"  Active Ingredient: {treatment['active_ingredient']}")
        print(f"  Dosage: {treatment['dosage']}")
        print(f"  Pre-harvest Interval: {treatment['pre_harvest_interval']} days")
        print(f"  Re-entry Interval: {treatment['re_entry_interval']}")
        print(f"  Effectiveness: {treatment['effectiveness_rate']:.0%}")
    
    # Example 2: Get treatments for Colorado Potato Beetle
    print("\n\n[EXAMPLE 2: Colorado Potato Beetle - Worldwide]")
    print("-" * 80)
    treatments = db.get_safe_treatment(
        "Colorado Potato Beetle",
        Region.WORLDWIDE,
        "potato"
    )
    for treatment in treatments:
        print(f"\nProduct: {treatment['product_name']}")
        print(f"PPE Required: {treatment['ppe_required']}")
        print(f"Restrictions: {treatment.get('restrictions', 'None')}")
    
    # Example 3: Unknown pest (fallback)
    print("\n\n[EXAMPLE 3: Unknown Pest (Fallback)]")
    print("-" * 80)
    fallback = db.get_safe_treatment(
        "Unknown Bug Syndrome",
        Region.EUROPE,
        "tomato"
    )
    print(f"Product: {fallback[0]['product_name']}")
    print(f"Dosage: {fallback[0]['dosage']}")
    print(f"Notes: {fallback[0]['environmental_notes']}")
    
    # Example 4: List all available pests
    print("\n\n[EXAMPLE 4: Available Pests in Database]")
    print("-" * 80)
    pests = db.get_all_pests()
    for pest in pests:
        print(f"  - {pest}")
    
    print("\n" + "=" * 80)
    print("✓ All examples completed successfully")
    print("=" * 80)
